# Generated by Django 6.0.1 on 2026-01-30 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Folder name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is public"
                    ),
                ),
                (
                    "is_starred",
                    models.BooleanField(default=False, verbose_name="Is starred"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="core.storagefolder",
                        verbose_name="Parent folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Folder",
                "verbose_name_plural": "Storage Folders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="File name"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="files/%Y/%m/%d/%H%M%S",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions={
                                    "7z",
                                    "aac",
                                    "avi",
                                    "bmp",
                                    "c",
                                    "cpp",
                                    "css",
                                    "csv",
                                    "doc",
                                    "docx",
                                    "flac",
                                    "gif",
                                    "go",
                                    "gz",
                                    "html",
                                    "java",
                                    "jpeg",
                                    "jpg",
                                    "js",
                                    "json",
                                    "mkv",
                                    "mov",
                                    "mp3",
                                    "mp4",
                                    "ogg",
                                    "pdf",
                                    "png",
                                    "ppt",
                                    "pptx",
                                    "py",
                                    "rar",
                                    "rs",
                                    "svg",
                                    "tar",
                                    "txt",
                                    "wav",
                                    "webm",
                                    "webp",
                                    "xls",
                                    "xlsx",
                                    "xml",
                                    "zip",
                                }
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(104857600)
                        ],
                        verbose_name="File size (bytes)",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="MIME type",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="SHA256 hash",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is public"
                    ),
                ),
                (
                    "is_starred",
                    models.BooleanField(default=False, verbose_name="Is starred"),
                ),
                (
                    "version_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Version count"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Download count"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last accessed"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.storagefolder",
                        verbose_name="Folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage File",
                "verbose_name_plural": "Storage Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("delete", "Delete"),
                            ("rename", "Rename"),
                            ("move", "Move"),
                            ("share", "Share"),
                            ("unshare", "Unshare"),
                            ("view", "View"),
                            ("create_folder", "Create Folder"),
                            ("permission_change", "Permission Change"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Activity type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="core.storagefile",
                        verbose_name="File",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="core.storagefolder",
                        verbose_name="Folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("share", "File shared with you"),
                            ("unshare", "Shared access removed"),
                            ("permission_change", "Permission changed"),
                            ("storage_limit", "Storage limit warning"),
                            ("file_deleted", "File deleted"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is read"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="core_notifi_user_id_cb8f07_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="Version number"
                    ),
                ),
                (
                    "file_data",
                    models.FileField(
                        upload_to="versions/%Y/%m/%d/", verbose_name="Version file"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="File hash"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(default=0, verbose_name="File size (bytes)"),
                ),
                (
                    "change_description",
                    models.TextField(blank=True, verbose_name="Change description"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is current version"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.storagefile",
                        verbose_name="File",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Version",
                "verbose_name_plural": "File Versions",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["file", "is_current"],
                        name="core_fileve_file_id_e13bc9_idx",
                    )
                ],
                "unique_together": {("file", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="storagefolder",
            index=models.Index(
                fields=["owner", "parent"], name="core_storag_owner_i_895d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagefolder",
            index=models.Index(
                fields=["owner", "is_public"], name="core_storag_owner_i_619c63_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storagefolder",
            unique_together={("owner", "parent", "name")},
        ),
        migrations.AddIndex(
            model_name="storagefile",
            index=models.Index(
                fields=["owner", "folder"], name="core_storag_owner_i_89f5f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagefile",
            index=models.Index(
                fields=["owner", "is_public"], name="core_storag_owner_i_c4f3aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagefile",
            index=models.Index(
                fields=["created_at"], name="core_storag_created_0044c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagefile",
            index=models.Index(
                fields=["file_hash"], name="core_storag_file_ha_5235a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storagefile",
            unique_together={("owner", "folder", "name")},
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="core_activi_user_id_33cb61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["activity_type"], name="core_activi_activit_44a51a_idx"
            ),
        ),
    ]
