# Generated by Django 5.2.10 on 2026-02-01 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagefile",
            name="is_trashed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is in trash"
            ),
        ),
        migrations.AddField(
            model_name="storagefile",
            name="original_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trashed_files",
                to="core.storagefolder",
                verbose_name="Original folder (before trash)",
            ),
        ),
        migrations.AddField(
            model_name="storagefile",
            name="trashed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trashed at"
            ),
        ),
    ]
