# Generated by Django 6.0.1 on 2026-03-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_storagefile_is_trashed_storagefile_original_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagefile",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="SHA256 hash"
            ),
        ),
    ]
