# Generated by Django 6.0.3 on 2026-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_file_hash_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.CharField(blank=True, max_length=500, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("share", "File shared with you"),
                    ("unshare", "Shared access removed"),
                    ("permission_change", "Permission changed"),
                    ("storage_limit", "Storage limit warning"),
                    ("file_deleted", "File deleted"),
                    ("comment", "New comment"),
                    ("news", "New article published"),
                    ("mention", "@mention"),
                    ("team_news", "Team-Site news"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="storagefile",
            name="file",
            field=models.FileField(
                upload_to="files/%Y/%m/%d/%H%M%S", verbose_name="File"
            ),
        ),
        migrations.AlterField(
            model_name="storagefile",
            name="size",
            field=models.BigIntegerField(default=0, verbose_name="File size (bytes)"),
        ),
    ]
