# Generated by Django 6.0.4 on 2026-05-07 12:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification_url_and_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="file_data",
            field=models.FileField(
                upload_to=core.models._company_version_upload_path,
                verbose_name="Version file",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("share", "File shared with you"),
                    ("unshare", "Shared access removed"),
                    ("permission_change", "Permission changed"),
                    ("storage_limit", "Storage limit warning"),
                    ("file_deleted", "File deleted"),
                    ("comment", "New comment"),
                    ("news", "New article published"),
                    ("mention", "@mention"),
                    ("team_news", "Team-Site news"),
                    ("message", "New chat message"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="storagefile",
            name="file",
            field=models.FileField(
                upload_to=core.models._company_file_upload_path, verbose_name="File"
            ),
        ),
    ]
