# Generated by Django 6.0.4 on 2026-05-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="messenger_c_room_id_d48ecd_idx",
            old_name="messenger_c_room_id_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="messenger_c_room_id_f8211f_idx",
            old_name="messenger_c_room_del_idx",
        ),
        migrations.AlterField(
            model_name="chatinvite",
            name="max_uses",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="0 = unlimited", verbose_name="Max uses"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="reactions",
            field=models.JSONField(
                default=dict,
                help_text='{"👍": ["user_id", ...], ...}',
                verbose_name="Reactions",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Private channels require an invitation to join.",
                verbose_name="Private",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="video_provider",
            field=models.CharField(
                blank=True,
                help_text="e.g. jitsi, daily, whereby — reserved for future use.",
                max_length=50,
                verbose_name="Video provider",
            ),
        ),
    ]
