# Generated by Django 6.0.1 on 2026-01-30 08:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Is used")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Is enabled"),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Secret key"
                    ),
                ),
                (
                    "backup_codes",
                    models.JSONField(default=list, verbose_name="Backup codes"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("totp", "Time-based OTP (Google Authenticator)"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        default="totp",
                        max_length=20,
                        verbose_name="Method",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone number"
                    ),
                ),
                (
                    "enabled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enabled at"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Two-Factor Auth",
                "verbose_name_plural": "Two-Factor Auth",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone number"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="Avatar",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("de", "Deutsch"),
                            ("en", "English"),
                            ("fr", "Français"),
                        ],
                        default="de",
                        max_length=5,
                        verbose_name="Language",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Berlin", max_length=63, verbose_name="Timezone"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        max_length=20,
                        verbose_name="Theme",
                    ),
                ),
                (
                    "storage_quota",
                    models.BigIntegerField(
                        default=5368709120,
                        help_text="Total storage allowed for this user",
                        validators=[django.core.validators.MinValueValidator(1048576)],
                        verbose_name="Storage quota (bytes)",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="Email verified"),
                ),
                (
                    "is_two_factor_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Two-factor authentication enabled"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last login"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password change"),
                            ("email_change", "Email change"),
                            ("profile_update", "Profile update"),
                            ("2fa_enable", "2FA enabled"),
                            ("2fa_disable", "2FA disabled"),
                            ("permission_grant", "Permission granted"),
                            ("permission_revoke", "Permission revoked"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_au_user_id_14f360_idx",
                    ),
                    models.Index(
                        fields=["action"], name="accounts_au_action_5ca9a9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        max_length=40,
                        unique=True,
                        verbose_name="Session key",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Device name"
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("windows", "Windows"),
                            ("macos", "macOS"),
                            ("linux", "Linux"),
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="OS type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="Last activity"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_us_user_id_91ed82_idx",
                    )
                ],
            },
        ),
    ]
