# Generated by Django 6.0.3 on 2026-03-20 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_mysite_hero_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Department"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Job title"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manager",
            ),
        ),
    ]
