# Generated by Django 6.0.3 on 2026-04-10 10:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_profile_company_and_area(apps, schema_editor):
    Company = apps.get_model("departments", "Company")
    Department = apps.get_model("departments", "Department")
    DepartmentMembership = apps.get_model("departments", "DepartmentMembership")
    UserProfile = apps.get_model("accounts", "UserProfile")

    default_company = Company.objects.order_by("id").first()

    for profile in UserProfile.objects.select_related("user").all():
        department = None

        if profile.department:
            department = Department.objects.filter(name=profile.department).order_by("id").first()

        if department is None:
            membership = DepartmentMembership.objects.filter(user_id=profile.user_id).order_by("id").first()
            if membership:
                department = Department.objects.filter(id=membership.department_id).first()

        updates = {}
        if department:
            updates["department_ref"] = department
            updates["company"] = department.company
            updates["department"] = department.name
        elif default_company:
            updates["company"] = default_company

        if updates:
            for field, value in updates.items():
                setattr(profile, field, value)
            profile.save(update_fields=list(updates.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_people_directory_fields"),
        ("departments", "0003_company_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="departments.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="departments.department",
                verbose_name="Area",
            ),
        ),
        migrations.RunPython(backfill_profile_company_and_area, migrations.RunPython.noop),
    ]
