# Generated by Django 6.0.1 on 2026-05-07 10:48
#
# NOTE:
# This migration originally duplicated the field addition from 0007_must_change_password.
# It is intentionally kept as a no-op that depends on the canonical migration to avoid
# conflicting/duplicate schema operations while preserving history.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_must_change_password'),
    ]

    operations = []
