# Generated by Django 6.0.4 on 2026-05-06 10:05
#
# NOTE:
# There was a second, duplicate migration file added later:
# `0007_userprofile_must_change_password.py`.
# That file is kept as a no-op (depending on this migration) to preserve history
# and avoid conflicting leaf nodes in the migration graph.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_company_landing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="Must change password on next login"
            ),
        ),
    ]
