# Generated by Codex on 2026-05-07
#
# Merge migration to reconcile duplicated `0007_*` files.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_must_change_password'),
        ('accounts', '0007_userprofile_must_change_password'),
    ]

    operations = []
