# Generated by Django 6.0.1 on 2026-01-30 08:07

import django.core.validators
import django.db.models.deletion
import sharing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=255, verbose_name="Group name"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Permission",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": ["storagefile", "storagefolder"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="group_shares_member_of",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Members",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_shares_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Share",
                "verbose_name_plural": "Group Shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=sharing.models.generate_public_link_token,
                        max_length=32,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Password hash"
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Permission",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "expires_after_downloads",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Expires after N downloads",
                    ),
                ),
                (
                    "allow_download",
                    models.BooleanField(default=True, verbose_name="Allow download"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View count"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Download count"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": ["storagefile", "storagefolder"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Link",
                "verbose_name_plural": "Public Links",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_active"],
                        name="sharing_pub_owner_i_ba1d8a_idx",
                    ),
                    models.Index(fields=["token"], name="sharing_pub_token_46056f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShareLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("accessed", "Accessed"),
                            ("downloaded", "Downloaded"),
                            ("password_changed", "Password changed"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Log",
                "verbose_name_plural": "Share Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="sharing_sha_action_ca843d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SharePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Permission type",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Granted at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_permissions",
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_share_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Granted by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Permission",
                "verbose_name_plural": "Share Permissions",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "permission_type"],
                        name="sharing_sha_user_id_31c32a_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="sharing_sha_content_771acb_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "content_type", "object_id", "permission_type")
                },
            },
        ),
        migrations.CreateModel(
            name="UserShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        default="view",
                        max_length=20,
                        verbose_name="Permission",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Share message")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": ["storagefile", "storagefolder"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shared with",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Share",
                "verbose_name_plural": "User Shares",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_active"],
                        name="sharing_use_owner_i_98d36b_idx",
                    ),
                    models.Index(
                        fields=["shared_with", "is_active"],
                        name="sharing_use_shared__cc36bf_idx",
                    ),
                ],
                "unique_together": {
                    ("owner", "shared_with", "content_type", "object_id")
                },
            },
        ),
    ]
