# Generated by Django 6.0.1 on 2026-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0005_teamsitenews_editorial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsitenews",
            name="tags",
            field=models.CharField(blank=True, max_length=255, verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="teamsitenews",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="View count"),
        ),
    ]
