# Generated by Django 6.0.3 on 2026-04-10 10:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_groupshare_company(apps, schema_editor):
    Company = apps.get_model("departments", "Company")
    UserProfile = apps.get_model("accounts", "UserProfile")
    GroupShare = apps.get_model("sharing", "GroupShare")

    default_company = Company.objects.order_by("id").first()

    for group in GroupShare.objects.select_related("department", "owner").all():
        company = None
        if group.department_id and getattr(group.department, "company_id", None):
            company = group.department.company
        else:
            profile = UserProfile.objects.filter(user_id=group.owner_id).first()
            if profile and profile.company_id:
                company = profile.company
        if company is None:
            company = default_company
        if company and group.company_id != company.id:
            group.company = company
            group.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_company_userprofile_department_ref"),
        ("departments", "0003_company_alter_department_options_and_more"),
        ("sharing", "0008_groupshare_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupshare",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_sites",
                to="departments.company",
                verbose_name="Firma",
            ),
        ),
        migrations.AlterField(
            model_name="groupshare",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_sites",
                to="departments.department",
                verbose_name="Bereich",
            ),
        ),
        migrations.RunPython(backfill_groupshare_company, migrations.RunPython.noop),
    ]
