# Generated by Django 6.0.4 on 2026-05-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0009_groupshare_department_auto_role"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="groupsharedepartmentautorole",
            new_name="sharing_gro_group_i_43238c_idx",
            old_name="sharing_gro_group_i_89c679_idx",
        ),
        migrations.RenameIndex(
            model_name="groupsharedepartmentautorole",
            new_name="sharing_gro_user_id_3c33c0_idx",
            old_name="sharing_gro_user_id_1a1471_idx",
        ),
    ]
