# Generated by Django 6.0.3 on 2026-04-10 10:14

import django.db.models.deletion
from django.db import migrations, models


def seed_default_company(apps, schema_editor):
    Company = apps.get_model("departments", "Company")
    Department = apps.get_model("departments", "Department")

    company, _ = Company.objects.get_or_create(
        slug="default-company",
        defaults={
            "name": "Default Company",
            "description": "Automatisch erzeugte Standardfirma fuer bestehende Daten.",
        },
    )
    Department.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_department_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Firmenname"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "employee_limit",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Mitarbeiterlimit kostenlos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Firma",
                "verbose_name_plural": "Firmen",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("create_department", "Kann Bereiche erstellen"),
                    ("manage_any_department", "Kann beliebige Bereiche verwalten"),
                ],
                "verbose_name": "Bereich",
                "verbose_name_plural": "Bereiche",
            },
        ),
        migrations.AlterModelOptions(
            name="departmentmembership",
            options={
                "ordering": ["role", "user__last_name", "user__username"],
                "verbose_name": "Bereichsmitgliedschaft",
                "verbose_name_plural": "Bereichsmitgliedschaften",
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="departments.company",
                verbose_name="Firma",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("company", "name"), ("company", "slug")},
        ),
        migrations.RunPython(seed_default_company, migrations.RunPython.noop),
    ]
