# Generated by Django 6.0.3 on 2026-04-10 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_company_owner_and_admins(apps, schema_editor):
    Company = apps.get_model("departments", "Company")
    UserProfile = apps.get_model("accounts", "UserProfile")

    for company in Company.objects.all():
        owner_id = company.owner_id
        if owner_id is None:
            profile = UserProfile.objects.filter(company_id=company.id).order_by("user_id").first()
            if profile:
                company.owner_id = profile.user_id
                company.save(update_fields=["owner"])
                owner_id = profile.user_id
        if owner_id:
            company.admins.add(owner_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_company_userprofile_department_ref"),
        ("departments", "0003_company_alter_department_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("create_company", "Kann Firmen erstellen"),
                    ("manage_any_company", "Kann beliebige Firmen verwalten"),
                ],
                "verbose_name": "Firma",
                "verbose_name_plural": "Firmen",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Firmenadmins",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="domain",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Hauptdomain"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Firmeninhaber",
            ),
        ),
        migrations.RunPython(backfill_company_owner_and_admins, migrations.RunPython.noop),
    ]
