# Generated by Django 6.0.1 on 2026-01-30 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the plugin",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=255, unique=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Plugin version (e.g., 1.0.0)", max_length=50
                    ),
                ),
                (
                    "author",
                    models.CharField(help_text="Plugin author name", max_length=255),
                ),
                ("description", models.TextField(help_text="Plugin description")),
                (
                    "zip_file",
                    models.FileField(
                        help_text="Uploaded ZIP file containing plugin code",
                        upload_to="plugins/%Y/%m/",
                    ),
                ),
                (
                    "extracted_path",
                    models.CharField(
                        blank=True,
                        help_text="Path where plugin files were extracted",
                        max_length=500,
                    ),
                ),
                (
                    "manifest",
                    models.JSONField(
                        default=dict, help_text="Plugin manifest data from plugin.json"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether plugin is enabled",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("active", "Active"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="inactive",
                        help_text="Current status of the plugin",
                        max_length=20,
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Python module name for dynamic importing",
                        max_length=255,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if plugin failed to load"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When plugin was uploaded",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When plugin was last activated",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification time"
                    ),
                ),
                (
                    "installed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who uploaded this plugin",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_plugins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin",
                "verbose_name_plural": "Plugins",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PluginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("activated", "Activated"),
                            ("deactivated", "Deactivated"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Detailed message about the action"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        help_text="Plugin this log entry is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="plugins.plugin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plugin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Log",
                "verbose_name_plural": "Plugin Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="plugin",
            index=models.Index(
                fields=["status", "enabled"], name="plugins_plu_status_879804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plugin",
            index=models.Index(
                fields=["module_name"], name="plugins_plu_module__8575fa_idx"
            ),
        ),
    ]
