# Generated by Django 6.0.1 on 2026-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="position",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                help_text="Position on file preview page (left, center, or right)",
                max_length=20,
            ),
        ),
    ]
