# Generated by Django 5.2.10 on 2026-02-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0002_plugin_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="is_local",
            field=models.BooleanField(
                default=False,
                help_text="True if plugin is a local folder (not uploaded ZIP)",
            ),
        ),
        migrations.AlterField(
            model_name="plugin",
            name="extracted_path",
            field=models.CharField(
                blank=True,
                help_text="Path where plugin files are located",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="plugin",
            name="zip_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded ZIP file (optional for local folder plugins)",
                null=True,
                upload_to="plugins/%Y/%m/",
            ),
        ),
    ]
