# Generated by Django 5.2.10 on 2026-02-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0003_add_local_plugin_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="has_settings",
            field=models.BooleanField(
                default=False, help_text="Whether this plugin has configurable settings"
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Plugin-specific configuration settings",
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="settings_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON schema defining available settings",
            ),
        ),
    ]
