# Generated by Django 6.0.3 on 2026-03-20 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=False, verbose_name="Anonyme Einreichungen erlaubt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_forms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="Beschriftung"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Kurztext"),
                            ("textarea", "Langtext"),
                            ("select", "Dropdown"),
                            ("radio", "Einfachauswahl"),
                            ("checkbox", "Mehrfachauswahl"),
                            ("date", "Datum"),
                            ("scale", "Skala (1–5)"),
                        ],
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "choices_json",
                    models.TextField(
                        blank=True, default="[]", verbose_name="Optionen (JSON)"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Platzhalter"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Pflichtfeld"),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms_builder.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Field",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms_builder.form",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FormAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_label", models.CharField(max_length=255)),
                ("value", models.TextField(blank=True)),
                (
                    "field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers",
                        to="forms_builder.formfield",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="forms_builder.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Answer",
            },
        ),
    ]
