# Generated by Django 6.0.1 on 2026-05-07 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Geplanter Start')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Geplantes Ende')),
                ('room_name', models.SlugField(blank=True, max_length=80, verbose_name='Raumname')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('running', 'Läuft'), ('ended', 'Beendet'), ('cancelled', 'Abgesagt')], db_index=True, default='planned', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.company')),
                ('invitees', models.ManyToManyField(blank=True, related_name='invited_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Eingeladene')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organisator')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-created_at'],
            },
        ),
    ]
