# Generated by Django 6.0.1 on 2026-01-30 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_files",
                    models.PositiveIntegerField(default=0, verbose_name="Total files"),
                ),
                (
                    "total_size",
                    models.BigIntegerField(
                        default=0, verbose_name="Total size (bytes)"
                    ),
                ),
                (
                    "backed_up_files",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Backed up files"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error message"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Backup",
                "verbose_name_plural": "Storage Backups",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_files",
                    models.PositiveIntegerField(default=0, verbose_name="Total files"),
                ),
                (
                    "total_folders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total folders"
                    ),
                ),
                (
                    "total_size",
                    models.BigIntegerField(
                        default=0, verbose_name="Total size (bytes)"
                    ),
                ),
                (
                    "total_versions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total versions"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Stats",
                "verbose_name_plural": "Storage Stats",
            },
        ),
        migrations.CreateModel(
            name="TrashBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                ("original_path", models.TextField(verbose_name="Original path")),
                ("size", models.BigIntegerField(verbose_name="Size (bytes)")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Expires at (auto-delete)"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": ["storagefile", "storagefolder"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trash",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trash Bin",
                "verbose_name_plural": "Trash Bins",
                "ordering": ["-deleted_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageQuotaAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("warning", "Warning - 80% used"),
                            ("critical", "Critical - 95% used"),
                            ("full", "Full - 100% used"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Alert type",
                    ),
                ),
                (
                    "usage_percent",
                    models.PositiveIntegerField(verbose_name="Usage percent"),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is acknowledged"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Quota Alert",
                "verbose_name_plural": "Storage Quota Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_acknowledged"],
                        name="storage_sto_user_id_35365e_idx",
                    )
                ],
            },
        ),
    ]
